# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
fail_fast: true
repos:
  - repo: local
    hooks:
      - id: fmt
        name: auto-format python source files
        entry: make fmt
        language: system
        pass_filenames: false
        always_run: true
      - id: mypy
        name: perform type-checking
        entry: make mypy
        language: system
        pass_filenames: false
        always_run: true
      - id: uv-lock-check
        name: check for uv-lock changes
        entry: uv lock --check
        language: system
        pass_filenames: false
        always_run: true
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: ^tests/data/
      - id: check-yaml
      - id: check-added-large-files
      - id: fix-byte-order-marker
      - id: detect-private-key
      - id: check-ast
      - id: check-toml
      - id: check-merge-conflict
