line-length = 120
indent-width = 4

target-version = "py312"

[lint]
select = [
    "E",        # pycodestyle errors
    "W",        # pycodestyle warnings
    "F",        # pyflakes
    "I",        # isort
    "B",        # flake8-bugbear
    "C4",       # flake8-comprehensions
    "UP",       # pyupgrade
    "A",        # flake8-builtins
    "C90",      # mccabe
    "Q",        # flake8-quotes
    "PERF",     # perflint
    "PT",       # flake8-pytest-style
    "RUF100",   # unused-noqa
    "T201",     # checks for print statements
    "FAST",     # fastapi
    "YTT",
]

external = ["WPS"]

[lint.mccabe]
max-complexity = 8

[format]